kanban_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('org/', include('organizations.urls')),
]

organizations/urls.py
from django.urls import path

from .views import (
    OrganizationDetailView,
    OrganizationListView,

)

urlpatterns = [
    path('all/', OrganizationListView.as_view(), name='orgs-all'),
    path('<int:pk>/', OrganizationDetailView.as_view(), name='org-detail')
]

users/urls.py
from django.urls import path

from .views import SignUpView, CustomUserDetailView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<int:pk>/', CustomUserDetailView.as_view(), name='user-detail'),
]

boards/models.py
from django.db import models
from organizations.models import Organization
from users.models import CustomUser


class Board(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    creator = models.ForeignKey(CustomUser, null=True, on_delete=models.SET_NULL)
    admins = models.ManyToManyField(CustomUser, related_name='admins', blank=True)

    def __str__(self):
        return self.title + ' > ' + self.organization.name


class Stage(models.Model):
    name = models.CharField(max_length=32)
    number = models.PositiveSmallIntegerField()
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + ' > ' + self.board.title
    

organizations/models.py
from django.db import models

from users.models import CustomUser 

class Organization(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(CustomUser, through='Membership', blank=True)

    def __str__(self):
        return self.name

class Membership(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)

tasks/models.py
from django.db import models

from boards.models import Stage

class Task(models.Model):
    title = models.CharField(max_length=256)
    description = models.TextField(null=True, blank=True)
    stage = models.ForeignKey(Stage, on_delete=models.CASCADE)
     

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    age = models.PositiveSmallIntegerField(null=True, blank=True)
    about = models.TextField(null=True, blank=True)
    telegram = models.SlugField(null=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'telegram', 'age', 'about')

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'telegram', 'age', 'about')

organizations/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Organization

class OrganizationListView(ListView):
    model = Organization
    template_name='orgs.html'

class OrganizationDetailView(DetailView):
    model = Organization
    template_name = 'org_detail.html'

tasks/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView

from .models import CustomUser

from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class CustomUserDetailView(DetailView):
    model = CustomUser
    template_name = 'user.html'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %} | Kanban Web App</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/org_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
    <h2>{{ object.name }}</h2>
    <p>{{ object.description }}</p>
    <a>
        {% for memship in object.membership_set.all %}
            <li>
                <b><a href="{% url 'user-detail' memship.user.pk %}">{{ memship.user }}</a></b>
                {% if memship.is_admin %}
                    <span style="color: green; ">admin</span>
                {% endif %}
            </li>
            
        {% endfor %}
    </ul>
{% endblock content %}

templates/orgs.html
{% extends 'base.html' %}

{% block title %}All Organizations{% endblock title %}

{% block content %}
    {% for org in object_list %}
    <div style = "border-left: 1px solid silver; border-bottom: 1px solid silver; margin-top: 20px; padding: 10px">
        <h2>{{ org.name }}</h2>
        <div><a href="{% url 'org-detail' org.id %}">open...</a></div>
        <p>{{ org.description }}</p>

        {% for user in org.participants.all %}
            <ul>
                <li>{{ user.username }}</li>
            </ul>
        {% endfor %}
    </div>
    {% endfor %}
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Sign Up">
    </form>
{% endblock content %}

templates/user.html
{% extends 'base.html' %}
{% block title %}{{ object.username }}{% endblock title %}

{% block content %}
    <h1>{{ object.username }}</h1>

    <h3>Email: <b>{{ object.email }}</b></h3>
    <hr>
    {% if object.about %}
    <div>
        <h3>About:</h3>
        <p>{{ object.about }}</p>
    </div>
    <hr>
    {% endif %}

    Organizations:
    <ul>
    {% for org in object.organization_set.all %}
        <li>
            <div>
                <a href="{% url 'org-detail' org.id %}"><h4>{{ org.name }}</h4></a>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endblock %}